create table
    public.category_types
(
    id         bigint generated by default as identity not null,
    name       text                                    not null,
    is_expense boolean                                 not null,
    constraint category_types_pkey primary key (id),
    constraint category_types_name_check check (
        (
            (length(name) >= 1)
                and (length(name) <= 32)
            )
        )
) tablespace pg_default;
