create table
    public.categories
(
    id              bigint generated by default as identity not null,
    name            text                                    not null,
    color_id        bigint null,
    type_id         bigint                                  not null,
    owner_id        uuid                                    not null,
    parent_category bigint null,
    constraint categories_pkey primary key (id),
    constraint categories_parent_category_fkey foreign key (parent_category) references categories (id) on delete cascade,
    constraint categories_color_id_fkey foreign key (color_id) references category_colors (id),
    constraint categories_type_id_fkey foreign key (type_id) references category_types (id),
    constraint categories_owner_id_fkey foreign key (owner_id) references auth.users (id) on delete cascade,
    constraint categories_name_check check (
        (
            (length(name) >= 1)
                and (length(name) <= 64)
            )
        )
) tablespace pg_default;