CREATE TABLE
    categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       TEXT                                    NOT NULL,
    color_id   BIGINT                                  NULL,
    type_id    BIGINT                                  NOT NULL,
    owner_id   UUID                                    NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT NOW(),

    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_color_id_fkey FOREIGN KEY (color_id) REFERENCES category_colors (id),
    CONSTRAINT categories_type_id_fkey FOREIGN KEY (type_id) REFERENCES category_types (id),
    CONSTRAINT categories_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users (id) ON DELETE CASCADE,

    CONSTRAINT categories_name_check CHECK (LENGTH(name) BETWEEN 1 AND 64)
);

ALTER TABLE "categories"
    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow access for users based on owner_id"
    ON "categories"
    AS PERMISSIVE
    FOR ALL
    TO authenticated
    USING (((SELECT auth.uid() AS uid) = owner_id))
    WITH CHECK (((SELECT auth.uid() AS uid) = owner_id));

CREATE FUNCTION prevent_category_type_change()
    RETURNS TRIGGER
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    IF NEW.type_id <> OLD.type_id THEN
        IF EXISTS (SELECT id FROM transactions WHERE category_id = NEW.id) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23505',
                MESSAGE = 'Cannot change category type while referenced by a transaction',
                DETAIL = 'Category ' || NEW.id || ' has a dependent transactions',
                HINT = 'Delete or reassign transactions before changing category type';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER prevent_category_type_change
    BEFORE UPDATE
    ON categories
    FOR EACH ROW
EXECUTE PROCEDURE prevent_category_type_change();