CREATE TABLE
    category_colors
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  TEXT                                    NOT NULL,
    red   SMALLINT                                NOT NULL,
    green SMALLINT                                NOT NULL,
    blue  SMALLINT                                NOT NULL,

    CONSTRAINT category_colors_pkey PRIMARY KEY (id),

    CONSTRAINT category_colors_name_check CHECK (LENGTH(name) BETWEEN 1 AND 32),
    CONSTRAINT category_colors_red_check CHECK (red BETWEEN 0 AND 255),
    CONSTRAINT category_colors_green_check CHECK (green BETWEEN 0 AND 255),
    CONSTRAINT category_colors_blue_check CHECK (blue BETWEEN 0 AND 255)
);