create table
    public.category_colors
(
    id    bigint generated by default as identity not null,
    name  text                                    not null,
    red   smallint                                not null,
    green smallint                                not null,
    blue  smallint                                not null,
    constraint category_colors_pkey primary key (id),
    constraint category_colors_name_check check (
        (
            (length(name) >= 1)
                and (length(name) <= 32)
            )
        ),
    constraint category_colors_red_check check (
        (
            (red >= 0)
                and (red <= 255)
            )
        ),
    constraint category_colors_green_check check (
        (
            (green >= 0)
                and (green <= 255)
            )
        ),
    constraint category_colors_blue_check check (
        (
            (blue >= 0)
                and (blue <= 255)
            )
        )
) tablespace pg_default;