CREATE TABLE wallets
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     TEXT                                    NOT NULL,
    balance  BIGINT                                  NOT NULL,
    owner_id UUID                                    NOT NULL,

    CONSTRAINT wallets_pkey PRIMARY KEY (id),
    CONSTRAINT wallets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users (id) ON DELETE CASCADE,

    CONSTRAINT wallets_balance_check CHECK (balance >= 0),
    CONSTRAINT wallets_name_check CHECK (LENGTH(name) BETWEEN 1 AND 32)
);

ALTER TABLE wallets
    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable access for users based on owner_id"
    ON wallets
    AS PERMISSIVE
    FOR ALL
    TO authenticated
    USING (((SELECT auth.uid() AS uid) = owner_id))
    WITH CHECK (((SELECT auth.uid() AS uid) = owner_id));